sonata_news:
    title:        Dashboard
    link:         https://admin.soyel.fr
    description:  Admin dashboard for soyel.fr website
    salt:         'DaymnItsSupposedToBeSecret'
    permalink_generator: sonata.news.permalink.collection # sonata.news.permalink.collection

    comment:
        notification:
            emails:   [email@example.org, email2@example.org]
            from:     no-reply@sonata-project.org
            template: 'SonataNewsBundle:Mail:comment_notification.txt.twig'

    admin:
        post:
            class:     Application\Sonata\NewsBundle\Admin\PostAdmin
