sonata_news:
    title:        Soyel's Blog
    link:         https://blog.soyel.fr
    description:  A blog about my journey in the real and the digital world
    salt:         %secret%
    permalink_generator: sonata.news.permalink.collection # sonata.news.permalink.collection

    comment:
        notification:
            emails:   [email@example.org, email2@example.org]
            from:     no-reply@sonata-project.org
            template: 'SonataNewsBundle:Mail:comment_notification.txt.twig'

    admin:
        post:
            class:     Application\Sonata\NewsBundle\Admin\PostAdmin
